NumPy Arrays

In [3]:
my_list = [1, 2, 3]

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(my_mat)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0, 100, 100) # It will return 100 number between 0 to 100 equally spaced

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

Identity Matrix, A matrix with all zeros but except the diagonal is ones

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.14030911, 0.33586966, 0.69435151, 0.55032944, 0.27653447])

In [15]:
np.random.rand(2, 2)

array([[0.91312906, 0.56621198],
       [0.67784521, 0.321098  ]])

In [16]:
np.random.randn(10)

array([ 0.5255598 ,  0.52934915,  1.39757935, -0.40421729, -1.07313147,
       -0.80719376,  1.14919644,  0.86413322,  0.84685287, -1.36527695])

In [17]:
np.random.randint(1, 100)

77

In [18]:
np.random.randint(1, 100, 10)

array([70, 23, 49, 78,  5, 70, 33, 50, 70, 22])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ran_arr = np.random.randint(0, 50, 10)

In [23]:
ran_arr

array([32, 19, 21, 19, 13,  1, 30,  7, 31, 42])

In [24]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ran_arr.max()

42

In [27]:
ran_arr.min()

1

In [28]:
ran_arr.argmax()

9

In [29]:
ran_arr.argmin()

5

In [31]:
arr.shape

(25,)

In [32]:
ran_arr.shape

(10,)

In [33]:
arr.dtype

dtype('int64')

In [34]:
arr = np.arange(0, 11)

In [35]:
arr[9]

9

In [36]:
arr[1:5]

array([1, 2, 3, 4])

In [37]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [38]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [39]:
arr[6:-1]

array([6, 7, 8, 9])

In [40]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [41]:
arr[0:5] = 100

In [43]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr = arr[0:6]

In [53]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [55]:
slice_of_arr[:] = 99

In [56]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [57]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_copy = arr.copy()

In [60]:
arr_copy[:]=100

In [61]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [62]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing 2d Array

In [63]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [64]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
arr_2d[1][2]

30

In [66]:
arr_2d[2, 1]

40

In [67]:
arr_2d[1, 2]

30

In [68]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr = np.arange(0, 11)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [72]:
bool_arr = arr > 5

In [73]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr<7]

array([0, 1, 2, 3, 4, 5, 6])

In [77]:
arr_2d = np.arange(50).reshape(5, 10)

In [78]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [79]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operations
- Array with Array
- Array with Scalers
- Universal Array Functions

In [80]:
arr = np.arange(0, 11)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [86]:
arr * 4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [87]:
arr - 823

array([-823, -822, -821, -820, -819, -818, -817, -816, -815, -814, -813])

In [90]:
arr / arr

/var/folders/m4/72hy_b8d3dj79xnn1lfg07sm0000gn/T/ipykernel_46453/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [91]:
1/arr

/var/folders/m4/72hy_b8d3dj79xnn1lfg07sm0000gn/T/ipykernel_46453/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [93]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [94]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [95]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [96]:
np.max(arr)

10

In [97]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [98]:
np.log(arr)

/var/folders/m4/72hy_b8d3dj79xnn1lfg07sm0000gn/T/ipykernel_46453/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])